/**
 * Idempotency for Asaas webhooks.
 *
 * Asaas retries on 5xx / 408 / 429 — the same payload may arrive multiple
 * times. We must NOT double-credit. The idempotency anchor is `paymentId`
 * (or `paymentId + event` if you process the same payment in multiple states).
 *
 * Pattern A — Postgres (recommended for production):
 *
 *   create table public.asaas_webhook_events (
 *     id bigint generated by default as identity primary key,
 *     payment_id text not null,
 *     event text not null,
 *     processed_at timestamptz not null default now(),
 *     unique (payment_id, event)
 *   );
 *
 *   -- on conflict do nothing → first writer wins, replays are no-ops.
 *
 * Pattern B — in-memory (for dev / tests only). DO NOT ship.
 *
 * Project: <%= projectName %>
 */

const seen = new Set<string>();

function key(paymentId: string, event: string): string {
  return `${paymentId}::${event}`;
}

/**
 * Returns true if this (paymentId, event) was already processed.
 * Replace with a real DB-backed check before going to production.
 */
export async function isReplay(paymentId: string, event: string): Promise<boolean> {
  return seen.has(key(paymentId, event));
}

/**
 * Mark as processed. In production this should be a DB insert with
 * `on conflict do nothing` so the check + write is atomic.
 */
export async function markProcessed(paymentId: string, event: string): Promise<void> {
  seen.add(key(paymentId, event));
}

/**
 * Test-only — clear the in-memory set. Don't call in production.
 */
export function __resetIdempotencyForTests(): void {
  seen.clear();
}
